name: opencm-local

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env
    container_name: ocm-postgres
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  minio:
    image: minio/minio:latest
    env_file:
      - .env
    entrypoint: ["minio"]
    command: ["server", "app/data", "--console-address", ":9001", "--address", ":9000"]
    container_name: ocm-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/app/data

volumes:
  pg_data:
  minio_data: